[package]
name = "cashconvert"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
text_io = {version = "~0.1.0"}
iso_currency = { version = "0.4.1", features = ["with-serde"] }